### ISSUE TITLE
Anchor link bug

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2-ph2#10]
@rubillionaire looks like there's a weird bug with the links in the video modules. The video link seems to be continuing onto the text for some reason.Not too sure exactly what's happening but we took it out of the CMS so it wouldn't show up broken on the live site but here are screenshots below. The 2 faculty names are links so maybe the source of the issue is somewhere there? That first part of the text "Admissions Officer Kara Skolnik joins Illustration faculty members" should not be a link. I think it might actually be because the whole block is nested in an `<a>` tag instead of just the title.

<img width="1792" alt="Screen Shot 2020-04-22 at 09 35 41" src="https://user-images.githubusercontent.com/6997772/79992647-c80a7e80-8481-11ea-97ee-d28a49f1be37.png">
<img width="1680" alt="Screen Shot 2020-04-22 at 09 39 13" src="https://user-images.githubusercontent.com/6997772/79992648-c8a31500-8481-11ea-9b75-965805bdcb65.png">

**Comment by rubillionaire** [comment]
@mmarol yup, you were right! links within links. i overlooked the fact that the description could carry a link, and made the entire block a link.

just pushed fixes to both .systems & .edu. you should be set to add the links back in.

let me know how it works!

**Comment by mmarol** [comment]
It's working thank you!
