### ISSUE TITLE
Accordion open by default

### ISSUE THREAD

**Issue by mmarol** [risd/risd-congratulations-v2-ph2#3]
@rubillionaire @cmiller02 could we have only the accordions for this page be open by default? Or for there to be an option in the CMS to set the content to be accordions or not? I don't think there's currently a way to have a list of dates without it being an accordion?
https://welcome-ph2.risd.systems/open-risd/

**Comment by cmiller02** [comment]
If it's not too time-consuming @rubillionaire I think that it might be a good idea to add a radio button or something to the Universal - Calendar Items content type that would allow us to select, for each entered calendar item, if we would like it to be set to collapsed or open. If it's a ton easier for you to hard-code it into the /open-risd/ page that the Universal - Calendar Items being pulled in be set to be open then we could go that route, but I'd say the first option would be better, especially as I could see us wanting to use this option again - even if it's next year. Thanks for writing this up @mmarol.

**Comment by rubillionaire** [comment]
@cmiller02 @mmarol i was able to add a `Show Description On Load` switch to the `Universal - Calendar Items`. When set to `true`, the calendar item's description will be showing on page load. If set to `false`, the description will be hiding behind a click of the item. The default value is `false`.

To test this, I turned the switch to `true` for the [Test:Early Decision: International Student Welcome ][test-item] `Universal - Calendar Items` entry. This entry is visible as toggled open on the [Info Sessions page][info-sessions].

[test-item]:https://welcome-ph2.risd.systems/cms/#/wh/content/universalcalendaritems/-L6vzv_GBQV9QVa8GZdg
[info-sessions]:http://welcome-ph2.risd.systems/next-steps/info-sessions/

**Comment by cmiller02** [comment]
This is great, @rubillionaire and working perfectly! @mmarol I flipped the switch for the three items on the /open-risd/ page, so I think we're all set with this! Going to close this out. Thanks to you both.
