### ISSUE TITLE
adjusting modal a bit for mobile

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2-ph2#5]
@rubillionaire please see below for a snapshot from slack with the details for this:

![Screen Shot 2020-03-13 at 1 33 18 PM](https://user-images.githubusercontent.com/14020234/76645507-80621000-652f-11ea-8c16-c09db9e59411.png)

**Comment by rubillionaire** [comment]
@cmiller02 @mmarol i have adjusted the modal styles on smaller screens to always show the close button. this meant scaling the modal content down on smaller screens. let me how it looks to you.

**Comment by cmiller02** [comment]
<img width="375" alt="Screen Shot 2020-03-16 at 1 20 52 PM" src="https://user-images.githubusercontent.com/14020234/76783989-48560980-6789-11ea-87ea-2bc73a344571.png">
<img width="367" alt="Screen Shot 2020-03-16 at 1 21 38 PM" src="https://user-images.githubusercontent.com/14020234/76783991-48eea000-6789-11ea-8266-6ba76fd9957c.png">

Here are the two devices where you couldn't see the x before - yay that you can now! what do you thinkn @mmarol ?

**Comment by rubillionaire** [comment]
@cmiller02 hmm, it shouldn't overlap. i can take a look at those. do you happen to know which devices those are? its not happening for me in chrome or firefox on desktop.

**Comment by cmiller02** [comment]
those are the samsung galaxy 8 and the iphone 8, that were the only ones that, before, i couldn't see the x on (so they prompted me to enter this issue)

**Comment by cmiller02** [comment]
@rubillionaire i just looked at all the devices I'd looked out on browserstack before and the modal seems to fit well in all, it's just the overlap of the x issue - so if you're able to sort that out we might be good to go.

**Comment by rubillionaire** [comment]
@cmiller02 i just pushed a change that should prevent the close button from being centered. let me know how it looks to you.

**Comment by cmiller02** [comment]
looks great now @rubillionaire - i looked at all 6 devices I had looked at before!

**Comment by rubillionaire** [comment]
@cmiller02 thanks for checking all those devices! nice to know what we've got will work for folks with a diverse array of devices.

this is deployed, i'll close the issue for now
