### ISSUE TITLE
adding covid banner to homepage

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2-ph2#7]
@rubillionaire per the slack conversation in #admissions we need to please add a covid banner to the top of the site:

so initial modal moment stays the same, it would just be whenever you aren't seeing the modal that you'd see the covid banner above the top, yellow welcome strip

We will need to add this to graduatestudy.risd.edu also. And can we add it to the homepage content types on both sites like the module in the homepage content type of www.risd.edu?:
<img width="896" alt="Screen Shot 2020-03-16 at 11 53 39 AM" src="https://user-images.githubusercontent.com/14020234/76776280-eabbc000-677c-11ea-8ddd-3d54aa1dfce0.png">

lastly, i think we'd like the banner background color to be changeable, so if we could input a hex color in a field in the cms that would be great.

@mmarol did I miss anything here?

**Comment by rubillionaire** [comment]
@cmiller02 @mmarol there is a test banner up on https://welcome-ph2.risd.systems/ and https://graduatestudy.risd.systems/

the type feels a little big on the undergrad site, but let me know what y'all think. happy to change things up tomorrow am before launching.

we can also take these one at a time. there was a bit of ease in taking care of both at the same time for me, and now both are operating with a consistent [baseline][notification-component] so i'll take it as you guys see fit to cross the finish line.

[notification-component]:https://github.com/risd/component-notification

**Comment by mmarol** [comment]
@rubillionaire I think having the the bar consistent in styling across the sites would be best.  I think the color would be the only thing to consider since it needs to pop and like wit grad study it doesn't. Treating it as an institutional thing as opposed to a site specific thing would be best.
Can we match the styling to edu?

**Comment by rubillionaire** [comment]
@mmarol good call! the notification styles have been updated to include the type specifications that match risd.edu

**Comment by cmiller02** [comment]
nothing left to do on this, right @mmarol and @rubillionaire. We've deployed, but just wanted to make sure nothing new had come up after deploying the site.

**Comment by rubillionaire** [comment]
@cmiller02 yeah this is okay to close up. i just wanted to get it over on https://graduatestudy.risd.edu/ as well. so its live and available on that site too.

i'll close this up for now.
