### ISSUE TITLE
Text with image on mobile view

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2-ph2#8]
Sorry to be brief here, this is per Rob's slack in #admissions:

Can we left justify and add padding between header and image

<img width="480" alt="Screen Shot 2020-03-17 at 11 24 24 AM" src="https://user-images.githubusercontent.com/14020234/76872473-d93ceb80-6842-11ea-8dc3-4747a06c0d6a.png">

**Comment by rubillionaire** [comment]
@cmiller02 the styles for these images has been updated to include padding, as is now visible here http://welcome-ph2.risd.systems/learning-at-risd/first-year-student-curriculum/

**Comment by cmiller02** [comment]
@mmarol does this look good to you? - thanks @rubillionaire

**Comment by mmarol** [comment]
@rubillionaire the text and image aren't going full width of the column?
<img width="649" alt="Screen Shot 2020-03-17 at 12 59 10" src="https://user-images.githubusercontent.com/6997772/76881216-38a0f880-684f-11ea-86d1-fc36ab80d434.png">

**Comment by rubillionaire** [comment]
@mmarol they don't go full width until the screen is smaller. i could make it go full screen sooner, but i think it'll look way too big. one of those edge cases that doesn't look good at every pixel width but makes sense at breakpoints. let me know what you think

**Comment by mmarol** [comment]
It just doesn't match the text box above it?

**Comment by rubillionaire** [comment]
totally misunderstood @mmarol . thanks for clarifying on slack.

this has been deployed, i'll close it up for now
