### ISSUE TITLE
adding quote/video module to homepage

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-congratulations-v2-ph2#9]
Can we please change the "Congratulations! We're excited to welcome you..." row to instead contain a centered, large quote with a video module below it. We are going to ask that Admissions give us the video to upload as a vimeo or youtube link. I believe that with youtube you can select the still image that will sit on the page that would have the play button on it-like the image that would represent this video on the homepage before it's clicked, but is vimeo the same? If not, we may need to add the capability to select a still image to display. (If a vimeo video would need this-since i get the feeling the start of the video wouldn't be great to display as the still, just let me know and I can see if 1) we can go youtube instead or 2) if we need to build in the select a still option in the CMS

Please see this link to Jay M's figma file. (This isn't completely approved but we're thinking it's safe enough to start on and perhaps small tweaks would then come up.)

https://www.figma.com/proto/SgbtHoMWsdS34rVD3SoyZ8/Phase-2?node-id=1107%3A358&viewport=171%2C483%2C0.125&scaling=min-zoom

**Comment by rubillionaire** [comment]
@cmiller02 thanks for the write up!

i added some new fields to the `Home` content type. these are only being used on the welcome-ph2.risd.systems templates, so you can preview the changes there.

there is a `Show Statement Quote` switch and `Statement Quote` field that will display the large quote from jay's mockup. if this is switched on, the `Statement` field does not show up.

there is also a `Show Statement Video` switch and `Statement Video` embedly field that will display a video per jay's mockup. if this is switched on, the `Statement` field does not show up.

if both of these are switched off, then the `Statement` field is rendered as seen on welcome.risd.edu.

@mmarol i used the [`sans-xl`][t-sans-xl] type size on the quote, it seemed the closest to your mockup. this is used in a few other places in the site so if we can switch to one of the other type specifications we already have, or define a specific one for this space. for the large white quotes i didn't think the xxxl we had was enough so i added an [`sans-xxxxl`][t-span-xxxxl] spec. this isn't used anywhere else so it would be very easy to switch up.

all content in these two modules is just placeholder, feel free to adjust the content as you check out the implementation.

let me know what you think!

[t-sans-xl]:https://github.com/risd/risd-congratulations-v2-ph2/blob/develop/scss/dependencies/_type.scss#L156-L159
[t-span-xxxxl]:https://github.com/risd/risd-congratulations-v2-ph2/blob/develop/scss/dependencies/_type.scss#L178-L182

**Comment by cmiller02** [comment]
This is looking great @rubillionaire 
@mmarol sorry for forgetting to put you on the issue originally

I still have to look at the fields Ruben set up in the CMS to see how everything works, but welcome-ph2.risd.systems looks great!

@mmarol how are things looking to you?

**Comment by mmarol** [comment]
@cmiller02 checking with Jordan and Huy. Huy's out today so he might have to look tomorrow.

**Comment by cmiller02** [comment]
just updating here @rubillionaire and @mmarol that we're trying to get Jordan/Huy approval today and as soon as we do I'll ask @rubillionaire to deploy. Since he set this up using switches in the CMS (yay Ruben) we can deploy and then, when we get the video, plug the video and quote into the CMS then and just flip the switch to show them.

**Comment by mmarol** [comment]
@rubillionaire outlining the changes based on figma+slack convo:

1. change quote size to 50px, 60px line-height
2. change quotation marks size to 200px
3. change max width of both the quote and video module to 20em (if type size is 50px)
4. add video title option with sans-l size (matching "online info sessions", "next steps" etc lower on the page)

**Comment by rubillionaire** [comment]
the changes that came from this issue have been deployed! im going to close it up for now.

**Comment by cmiller02** [comment]
@rubillionaire 

Below is from our slack conversation earlier today about the need to a still image upload for the Rosannne video:

Carrie Miller 
need to ask you to do one small thing to the welcome homepage tomorrow. You know how you'd made the switches so we can turn on the quote and presidential video? It's looking like, instead of us picking a still from the video to be what you see on the homepage the president is really picky about photos of herself and will probably want to go with one that is an upload (a professional photo). If I spin up a github issue for you, could you prioritize this for tomorrow? (is this making sense? - and if you want to wait to deploy welcome till tomorrow to include both today's github issue and tomorrow's that's great)

Rubén Rodríguez  4:06 PM
yeah for sure. that is do-able. im going to take a quick look at the video to verify the implementation path

Carrie Miller  4:06 PM
great, and I'll get out of the homepage in the cms just in case. we were hoping we could just use youtube to select something she'd like but we don't think that will work for her

Rubén Rodríguez  4:08 PM
cool cool
4:10
the only thing i’ll need to know is whether the video will be on youtube or vimeo. either one has hooks for starting a video on click. so we can maintain the one click behavior with her separately uploaded video
4:10
oh, and a “play” icon would be useful to get from @mmarol 

Carrie Miller  4:10 PM
awesome. maybe i can confirm now, will ask lauren - ah good, thanks for mentioning
4:12
ok lauren says youtube!
4:12
will reach out to jay now

**Comment by cmiller02** [comment]
@rubillionaire - IMPORTANT NOTE: please ignore everything in my above comment. I was under the impression that we couldn't select a still photo on youtube that ISN'T a frame of the video itself. My apologies! SO - this means that we can close this ticket after all, as we don't need a still image upload feature on the homepage of the CMS anymore. So, going to close this out and sorry for the confusion.
